# -*- coding: utf-8 -*-
"""Analisis Sentimen Komen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U75y8m0pU7gLEVEVF9C5t6pf5Kb6BgCK
"""

import string
import pandas as pd
import numpy as np
import re

filename = "Youtube_scrapping.csv"
data = pd.read_csv(filename, encoding = 'latin-1')
data.head(20)

data.info()

data.shape

data = data.dropna()
data.isnull().sum()

data.drop_duplicates(inplace=True)
data.duplicated().sum()

data.drop(columns = ['nama', 'like_count'], inplace = True)
data.columns = ['text']
data.head()

# Case Folding: Mengubah semua teks menjadi huruf kecil
data['komen case folding'] = data['text'].str.lower()

print("\n Setelah Case Folding:")
(data.head(20))

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

data = data.dropna(subset=['komen case folding'])

# Tokenizing: proses menguraikan suatu teks atau dokumen menjadi unit-unit yang lebih kecil yang disebut dengan token
data['komen tokenized'] = data['komen case folding'].apply(word_tokenize)

print("\n Data Setelah Tokenizing:")
(data.head(20))

from nltk.corpus import stopwords
import re
nltk.download('stopwords')

# Normalization: Hapus karakter khusus, angka, dan kata-kata berhenti
stop_words = set(stopwords.words('indonesian'))
data['komen normalized'] = data['komen tokenized'].apply(lambda tokens: [word for word in tokens if word.isalpha() and word not in stop_words])
print("\nData Setelah Normalization:")
(data.head(20))

pip install Sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
# Stemming menggunakan Snowball Stemmer untuk Bahasa Indonesia
factory = StemmerFactory()
stemmer = factory.create_stemmer()
data['komen stemming'] = data['komen normalized'].apply(lambda tokens: [stemmer.stem(word) for word in tokens])
print("\nData Setelah Stemming:")
(data.head(20))

# Data Komen Bersih
data['komen bersih'] = data['komen normalized'].apply(lambda tokens: ' '.join([stemmer.stem(word) for word in tokens]))

print("\nData Clean:")
data.to_csv("dataset_clean.csv", index=False)
(data.head(20))

from wordcloud import WordCloud
import matplotlib.pyplot as plt

#reading the database
data = pd.read_csv("dataset_clean.csv")

#Bar chart with text against komen stemming
plt.bar(data['text'], data['komen stemming'])

plt.title("Bar Chart")

#setting the X and Y labels
plt.xlabel('text')
plt.ylabel('komen stemming')

#adding the legends
plt.show()